### ISSUE TITLE
Can not specify a code

### ISSUE THREAD

**Issue by fidian** [nathanbuchar/node-gitio#3]
I attempted to shorten my URL with a specified code but failed to do so.

```
$ gitio shrink https://raw.githubusercontent.com/fidian/ansi/master/ansi -c ansi

https://git.io/vMGqF  ✔ copied to clipboard
```

I expect the code would be `ansi` instead of `vMGqF`.

**Comment by fidian** [comment]
Perhaps this is because that URL was already shortened and instead of granting another short code the service decided to reuse the old one?  I did not shorten it earlier except with this tool.  When I tried again with `curl` it gave me the same `vMGqF` code.  Changing the URL allowed me to shorten it using the correct code.

Closing because this doesn't appear to be an issue with the tool but more of a problem on the API.

**Comment by nathanbuchar** [comment]
> Perhaps this is because that URL was already shortened 

Yes, that's what happens :(
